### ISSUE TITLE
Clarification needed on the input RGB format

### ISSUE THREAD

**Issue by zorrozork** [google/butteraugli#53]
The butteraugli.h header contains this comment:

> // Value of pixels of images rgb0 and rgb1 need to be represented as raw
> // intensity. Most image formats store gamma corrected intensity in pixel
> // values. This gamma correction has to be removed, by applying the following
> // function:
> // butteraugli_val = 255.0 * pow(png_val / 255.0, gamma);
> // A typical value of gamma is 2.2. It is usually stored in the image header.
> // Take care not to confuse that value with its inverse. The gamma value should
> // be always greater than one.
> // Butteraugli does not work as intended if the caller does not perform
> // gamma correction.

Is this correct and a conversion to "raw intensity" is needed for the input images?
And if so is the result of the above mentioned gamma correction that the input is in linear RGB? So for example when applied to standard definition video with matrix '601' the frames should be converted to linear RGB before applying Butteraugli? Thanks!

**Comment by jyrkialakuijala** [comment]
On Sun, Feb 24, 2019 at 2:03 PM zorrozork <notifications@github.com> wrote:

> Is this correct and a conversion to "raw intensity" is needed for the
> input images?
>
Yes.

> And if so is the result of the above mentioned gamma correction that the
> input is in linear RGB? So for example when applied to standard definition
> video with matrix '601' the frames should be converted to linear RGB before
> applying Butteraugli? Thanks!
>
You need to convert into linear RGB light where RGB are sRGB. These values
may be (slightly) negative for wide gamut use. The normalization value of
255 corresponds roughly to 120-200 nits.

**Comment by zorrozork** [comment]
Thanks for the clarification, it's all clear now.
